package com.eden.bonvoyage.core.models.room;

public enum Amenities {
  WIFI, PISCINA, SPA, ACADEMIA, RESTAURANTE, ESTACIONAMENTO, BAR, AR_CONDICIONADO, COZINHA,
  LAREIRA, VISTA_PARA_O_MAR, JARDIM, HIDROMASSAGEM, GARAGEM_PRIVATIVA, TV_SMART, FRIGOBAR
}
